---
title: "Mini-Project 2"
author: "Ben Raivel, Jordy Perry Greene, Ben Moss-Horwitz"
date: "2019-03-24"
output: 
  html_document:
    code_folding: hide
---


## Loading the data


##################
WHAT WE NEED TO DO
##################
-Annotate
-Write analysis
-Write single-sentence analysis overview
-"providing context or background useful in interpreting the graphic"
-Make graph look pretty


```{r, message = FALSE}
#This is our setup block, where we initialize everything
#we first get tidyverse
library(tidyverse)
#and then load in all of our data
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
#finally, to help with our join, we rename the ID column in candidates to match that of house_elections
candidates <- candidates %>%
  rename("fec_id" = cand_id)
```

```{r, message = FALSE}
#we set up our final dataset, which will be joined with other sets later
usefulData <- candidates %>%
  #we get some data from house_elections
  inner_join(house_elections, by = "fec_id") %>%
  #and select only the useful columns
  select(fec_id, incumbent, ge_winner)
#setting up our data set for positive contributions
contributionPositives <- contributions %>%
  #we select only the useful columns
  select(cand_id, transaction_amt) %>%
  #and filter any negative contributions out
  filter(transaction_amt > 0) %>%
  #we use group_by and summarize to make 3 columns: totalPos, the total amount of money added up from all positive contributions, avgPos, the average positive contribution, and numberPos, the amount of postive contributions recieved
  group_by(cand_id) %>%
  summarize(totalPos = sum(transaction_amt), avgPos = mean(transaction_amt), numberPos = n()) %>%
  #only take canadates with any contriubitons, because those will be the people we are looking at
  filter(numberPos != 0)
#finally, we rename to prepare for a join
contributionPositives <- contributionPositives %>%
  rename("fec_id" = cand_id)
#this is the same as above, but for negative contributions only. The only difference is that we don't want to get rid of people without any negative contributions, because if they have positive contributions they will still be useful to our data
contributionNegatives <- contributions %>%
  select(cand_id, transaction_amt) %>%
  filter(transaction_amt < 0) %>%
  group_by(cand_id) %>%
  summarize(totalNeg = sum(transaction_amt), avgNeg = mean(transaction_amt), numberNeg = n())
#and rename for the join
contributionNegatives <- contributionNegatives %>%
  rename("fec_id" = cand_id)
#now we join the positives to our final set
usefulData <- usefulData %>%
  inner_join(contributionPositives, by = "fec_id")
#and join the negatives
usefulData <- usefulData %>%
  left_join(contributionNegatives, by = "fec_id")
#we replace all the NAs from the people who had positive contributions but no negative contributions with zeroes, so that it doesn't break our graph
usefulData[is.na(usefulData)] <- 0
#now we create our final data set, which averages the contributions among ALL candidates
finalSet <- usefulData %>%
  group_by(incumbent, ge_winner) %>%
  summarise(money = mean(totalPos))
```

```{r}
labels <- c("FALSE" = "Challengers", "TRUE" = "Incumbent")
finalSet %>%
  ggplot(aes(x = ge_winner, y = money, fill = ge_winner)) +
  theme(panel.background = element_rect(fill = 'white'), legend.title = element_blank()) +
  ggtitle("Money spent on elections for incumbents vs challengers") +
  geom_col() +
  scale_fill_manual(values = c("#a84521", "#20a866")) +
  facet_wrap("incumbent", labeller = labeller(incumbent = labels))+
  scale_y_continuous(limits=c(0,3000000), name = "Total positive contributions", breaks = c(0,1000000,2000000,3000000), labels = c("$0", "$1m", "$2m","$3m")) +
  scale_x_discrete(name = "", labels = c("Lost", "Won"))
```

```{r}
finalSet <- usefulData %>%
  group_by(incumbent, ge_winner) %>%
  summarise(moneyNeg = mean(totalNeg))
```

```{r}
finalSet %>%
  ggplot(aes(x = ge_winner, y = moneyNeg, fill = ge_winner)) +
  
  geom_col()+
  facet_wrap("incumbent")
```

Github Repository Link:
https://github.com/benraivel/sds192-mp2